@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

title System Context Diagram for Car Dealership System

Person(employee, "Employee", "Employee of the car dealership")
Person(customer, "Customer", "Customer of the car dealership")
System(car_dealership, "Car Dealership System", "allows employees to manage cars and customers")

Rel(employee, car_dealership, "Tracks inventory and customer purchases", "uses")
Rel(customer, car_dealership, "View vehicle for sales", "uses")


'SHOW_LEGEND()
@enduml